### ISSUE TITLE
Why Right([1]) == Right([1]) is false

### ISSUE THREAD

**Issue by akbarpulatov** [spebbe/dartz#100]
Why `Right([1]) == Right([1])` is `false` ?

**Comment by spebbe** [comment]
Hi @akbarpulatov!
It is because `[1] == [1]` is `false` in Dart. This is a behaviour of Dart `List`s in general and not specific to `dartz`. See #80, #45 and #39 for longer explanations.

**Comment by akbarpulatov** [comment]
Thank you for your response. Closing this issue with this link then: https://stackoverflow.com/questions/10404516/how-can-i-compare-lists-for-equality-in-dart
