### ISSUE TITLE
Convenience methods on Set: filter, partition, map

### ISSUE THREAD

**Issue by rich-j** [spebbe/dartz#11]
Another convenience request - this time for `Set`:

    ISet<A> filter(bool predicate(A a))

    Tuple2<ISet<A>, ISet<A>> partition(bool f(A a))

Yes, these are easy `foldLeft`s but I need to provide the new empty `Set`'s `Order` which the underlying implementation already knows (and I need to `import`).

I also had a case where I wanted to `map`:

    ISet<B> map<B>(B f(A a))

but this would have the problem of what `Order` to use. 

    ISet<B> map<B>(Order<B> order, B f(A a))

doesn't read as well... I'm good with `foldLeft` for this.

Thanks

**Comment by spebbe** [comment]
Hi! 'filter' and 'partition' look like good additions -- i'll add them in the next release!

'map' is missing more or less for the reason you gave above. 'map' is so closely associated with the Functor type class and its associated laws. The signature and implementation of 'map' for ISet wouldn't fit that definition very well.
Even so, it would be a useful operation -- would `ISet<B> transform<B>(Order<B> order, B f(A a))` be ok to make it more clear that ISet is not a Functor? Or am i just fixating too much on the category theoretical details? :-)

**Comment by rich-j** [comment]
I like the `transform` operation - yes, `map` is such a fundamental operation that trying to force it with a "non standard" API just doesn't feel right. I think you're doing a good job balancing between theory and practical implementation given Dart 2.x type system limitations.

**Comment by spebbe** [comment]
Hi! I just released 0.8.4 with filter, where, partition and transform added to ISet. Also added to the 0_9_0_wip_2 branch through rebase + force push.
