### ISSUE TITLE
IList.option

### ISSUE THREAD

**Issue by modulovalue** [spebbe/dartz#17]
I couldn't find a mapping from IList to Option where
The empty list is a `None`
and the non-empty list is a `Some` containing that list.

This would really be useful in flutter where one might want to show an alternative Widget for an empty list and map a non-empty list to a ListView.

Example
```dart
myIList.option.fold(emptyWidget, listView)
```

Do you think this would fit IList?

**Comment by spebbe** [comment]
Thanks -- looks useful! In the spirit of your previous PR, maybe this is also a good time to safely expose head and tail on `Cons` combined with a method `Option<Cons<A>> asCons()` on `IList`? I'll make a PR and get back to you.

**Comment by rich-j** [comment]
The above `toOption` would be useful. Also a simple `isEmpty` would be useful too. Today to check for an empty list I use `myIList.headOption.isNone()`.

**Comment by spebbe** [comment]
@modulovalue, @rich-j: sorry for slow response -- on vacation.
Please have a look at PR #21 and see if it looks ok!
@rich-j : I didn't add `isEmpty` in this PR. I tend to do `myIList == nil()`, possibly with a cached instance of `nil()`, but I'd be happy to add `isEmpty` separately if you still want it.

**Comment by spebbe** [comment]
Sorry, took a bit of time to get out, but this is now released as 0.8.6 + rebased onto `0_9_0_wip_2`!
