### ISSUE TITLE
Compile error on Dart 2.4.0

### ISSUE THREAD

**Issue by xsobolx** [spebbe/dartz#18]
I've got this compiler message:

> Compiler message:                                                       
...pub-cache/hosted/pub.dartlang.org/dartz-0.8.5/lib/src/io.dart:69:7: Error: Class 'FreeMonad<IOOp> with MonadCatch<Free<IOOp, dynamic>>' inherits multiple members named 'bind' with incompatible signatures.
Try adding a declaration of 'bind' to 'FreeMonad<IOOp> with MonadCatch<Free<IOOp, dynamic>>'.
class IOMonad extends FreeMonad<IOOp> with MonadCatch<Free<IOOp, dynamic>> { // ignore: inconsistent_method_inheritance
      ^                                                                 
...pub-cache/hosted/pub.dartlang.org/dartz-0.8.5/lib/src/free.dart:79:24: Context: This is the inherited member.
  @override Free<F, B> bind<A, B>(Free<F, A> fa, Free<F, B> f(A a)) => fa.bind(f);
                       ^^^^                                             
...pub-cache/hosted/pub.dartlang.org/dartz-0.8.5/lib/src/monad.dart:4:5: Context: This is the inherited member.
  F bind<A, B>(covariant F fa, covariant F f(A a));                     
    ^^^^                                                                
...pub-cache/hosted/pub.dartlang.org/dartz-0.8.5/lib/src/io.dart:69:7: Error: Class 'IOMonad' inherits multiple members named 'bind' with incompatible signatures.
Try adding a declaration of 'bind' to 'IOMonad'.                        
class IOMonad extends FreeMonad<IOOp> with MonadCatch<Free<IOOp, dynamic>> { // ignore: inconsistent_method_inheritance
      ^^^^^^^                                                           
...pub-cache/hosted/pub.dartlang.org/dartz-0.8.5/lib/src/free.dart:79:24: Context: This is the inherited member.
  @override Free<F, B> bind<A, B>(Free<F, A> fa, Free<F, B> f(A a)) => fa.bind(f);
                       ^^^^                                             
...pub-cache/hosted/pub.dartlang.org/dartz-0.8.5/lib/src/monad.dart:4:5: Context: This is the inherited member.
  F bind<A, B>(covariant F fa, covariant F f(A a));                     
    ^^^^                                                                

Dart version:
> Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "macos_x64"

**Comment by spebbe** [comment]
Thanks for reporting -- will have a look!

**Comment by spebbe** [comment]
@xsobolx: thanks for waiting. on vacation, but have now added a solution in PR #22.
I'll merge it and make a new release if no one is opposed.

@modulovalue, thanks for your solution! I've commented on your PR.

**Comment by xsobolx** [comment]
That's good news! Thank you!

**Comment by rich-j** [comment]
Could use this in branch `0_9_0_wip_2` too.

Flutter beta channel just updated to v1.8.3 which uses Dart 2.5.0. I forked and merged your PR #22 - it works.

**Comment by spebbe** [comment]
@xsobolx, @rich-j -- Sorry for the radio silence -- been on vacay!
This has now been released as 0.8.6 and also rebased onto `0_9_0_wip_2`.
