### ISSUE TITLE
Dart 2.x strong mode causes IList Nil to throw a runtime CastError

### ISSUE THREAD

**Issue by rich-j** [spebbe/dartz#2]
I'm a Scala developer who's starting to use Dart and am excited to see your dartz library. I'm living on the bleeding edge and using Dart 2.0.0-dev.39.0. Option and Either work but when I try to use IList I get a runtime CastError. For example, this code from you test suite `final l1 = ilist([1,2,3,4]);` compiles okay but throws the following error when compiled for Dart Angular with DDC and running in Chrome:

    _js_helper.CastErrorImplementation.new {message: "CastError: Casting value of type '_Nil' to type 'IList<int>' which is incompatible in strong mode"

I've tried other variations of using IList but all result in the above error. 

Edit: The runtime CastError also happens for Option None, however I can explicitly cast the object creation like `Option<String> s4 = new None<String>();`. This cast isn't possible for Nil since the `_Nil` class constructor is private.

Maybe this issue is a more general question of when do you expect to be Dart 2.x compatible?

**Comment by spebbe** [comment]
Hi! Glad to hear that you're excited!

At the moment, the Dart 2 eco system is... interesting, with dartz running fine in the analyzer, vm and dart2js, but not under DDC - the new incremental js compiler. As far as I know, DDC is the only part of the tool chain that currently implements the runtime parts of the new type system and it is still very wobbly, unbreaking old things and breaking new things with every dev release.

dartz contains a couple of nasty, but previously safe, casts that cover up for some features lacking in the Dart type system (old and new), enabling some code reuse and reducing unnecessary allocations. These casts are currently punishing me on DDC...

I've pushed some initial work on DDC compatibility on the ddc_compat (https://github.com/spebbe/dartz/tree/ddc_compat) branch. Basic operations on collections, Option, Either and Free now work on DDC, but a lot of things are still broken. Many of the changes also incur unnecessary allocations and type checks on the dart vm and in dart2js. Please give it a spin if you feel like it!

I probably won't merge these changes to master until DDC and Dart 2 have stabilized and/or I've found better solutions with minimal performance impact on the vm/dart2js.

Hope that helps!

/Björn

**Comment by rich-j** [comment]
Thanks for the fast response. I am able to use your ddc_compat branch to get past the runtime error. Here's the `pubspec.yaml` dependency I used:

    dartz:
      git:
        url: https://github.com/spebbe/dartz
        ref: ddc_compat

I agree that the current Dart 2.X eco system is challenging. This dartz dependency override was straightforward. However, I encountered other dependency issues because I updated all of my dependencies including Angular which resulted in mismatched dependencies that required figuring out "dependency_overrides".

An Angular specific usage note for `IList` with `*ngFor` - when I used an `IList` directly  I received a runtime error of:

    NgFor only supports binding to something that implements the `Iterable` interface, such as `List`.

I created an Angular `toIterable` pipe that calls the `.toIterable()` function. Keeping data as an `IList` allows filtering, mapping and sorting to be defined in the component. The final display then does a single conversion to an iterable using a pipe:

    <li *ngFor="let person of (sortedPersons | toIterable)">

**Comment by spebbe** [comment]
Really cool! -- I haven't tried AngularDart much, but it's great to see that it's possible to integrate with! I can recommend using dartz together with uix (https://pub.dartlang.org/packages/uix), where fully immutable state stores, Free monad interpreters and streams combine into a really nice and efficient React+Redux-like environment, but with composable actions and much better type safety.

Regarding Iterable, it would of course be convenient to have IList/IVector/etc implement it directly, but I'm hoping to keep an API consisting (almost) only of pure, total functions that never return null or throw exceptions intentionally. Iterable forces implementations to have many partial/impure methods. The toIterable()/iterator() methods, while inconvenient, make it explicit in the code when you are leaving the warm and safe FP world.

I'm hopeful that I'll be able to have the full test suite passing on DDC soonish. I'll keep this ticket open until things have stabilized.

**Comment by rich-j** [comment]
We're porting an application written in Typescript/Angular to Dart/Angular so we can build the mobile app with Dart/Flutter. We have a fair amount of client-side code so Dart will finally let us run "natively" on iOS/Android/Web.

I'll take a look at uix although probably mostly for inspiration.  Our architecture is already Redux-like with changes applied to an immutable data layer (with server sync) and then pushed to the U/I through streams (observables on Typescript).

I like your approach with `.toIterable()` to leave "the warm and safe FP world".  Well, at first I was disappointed that `IList` didn't implement `Iterable` directly, but after thinking about it I realized that creating an Angular pipe to do this no-overhead "conversion" keeps the data structures pure as long as possible. On the "entry side" I just found the `optionOf<A>(A value)` function to banish nulls.

**Comment by gedw99** [comment]
I was thinking about trying this for flutter also. Did you get a working implementation yet ??
Really cool lib btw !!!

**Comment by spebbe** [comment]
Thanks @gedw99!
The ddc_compat branch (see comment from @rich-j for usage) is still the closest thing to a working implementation there is. Basic things seem to work for now, but new dev versions of DDC change semantics so much that I don't dare commit to a strategy until things have stabilized.

In the end, I think that the stand alone type class instances (OptionM, etc.), as they are implemented now, will have to go... They will probably never be able to coexist with proper typing in Dart 2 DDC. They never really did in Dart 1 either, but there you could cheat :-)

**Comment by rich-j** [comment]
Upgrading to `Dart VM version: 2.0.0-dev.66.0 (Fri Jun 29 11:19:05 2018 +0200) on "macos_x64"` now causes failures when running unit tests under the VM (Google recently made Dart 2.0 the default for the VM).

We are using your `ddc_compat` branch and still run fine under DDC. Here are the errors that now cause all unit tests to fail when run in the VM:

    Unable to spawn isolate: file:///Users/richj/.pub-cache/git/dartz-dab47747ddffe55cafdddabba181c40bcbbb2de7/lib/src/ilist.dart:156:36: Error: The parameter 'l2' of the method 'IList::plus' has type dartz::IList<dartz::IList::A>, which does not match the corresponding type in the overridden method (dartz::IList<dynamic>).
    Change to a supertype of dartz::IList<dynamic> (or, for a covariant parameter, a subtype).
      @override IList<A> plus(IList<A> l2) => foldRight(l2, (e, p) => new Cons(e, p));
                                       ^
    file:///Users/richj/.pub-cache/git/dartz-dab47747ddffe55cafdddabba181c40bcbbb2de7/lib/src/list.dart:11:37: Error: The parameter 'f1' of the method 'ListTraversableMonadPlus::plus' has type dart.core::List<dartz::ListTraversableMonadPlus::plus::A>, which does not match the corresponding type in the overridden method (dart.core::List<dynamic>).
    Change to a supertype of dart.core::List<dynamic> (or, for a covariant parameter, a subtype).
      @override List<A> plus<A>(List<A> f1, List<A> f2) => new List.from(f1)..addAll(f2);
                                        ^
    file:///Users/richj/.pub-cache/git/dartz-dab47747ddffe55cafdddabba181c40bcbbb2de7/lib/src/list.dart:11:49: Error: The parameter 'f2' of the method 'ListTraversableMonadPlus::plus' has type dart.core::List<dartz::ListTraversableMonadPlus::plus::A>, which does not match the corresponding type in the overridden method (dart.core::List<dynamic>).
    Change to a supertype of dart.core::List<dynamic> (or, for a covariant parameter, a subtype).
      @override List<A> plus<A>(List<A> f1, List<A> f2) => new List.from(f1)..addAll(f2);
                                                    ^
    file:///Users/richj/.pub-cache/git/dartz-dab47747ddffe55cafdddabba181c40bcbbb2de7/lib/src/option.dart:23:38: Error: The parameter 'o2' of the method 'Option::plus' has type dartz::Option<dartz::Option::A>, which does not match the corresponding type in the overridden method (dartz::Option<dynamic>).
    Change to a supertype of dartz::Option<dynamic> (or, for a covariant parameter, a subtype).
      @override Option<A> plus(Option<A> o2) => orElse(() => o2);
                                         ^
    file:///Users/richj/.pub-cache/git/dartz-dab47747ddffe55cafdddabba181c40bcbbb2de7/lib/src/ivector.dart:44:40: Error: The parameter 'fa2' of the method 'IVector::plus' has type dartz::IVector<dartz::IVector::A>, which does not match the corresponding type in the overridden method (dartz::IVector<dynamic>).
    Change to a supertype of dartz::IVector<dynamic> (or, for a covariant parameter, a subtype).
      @override IVector<A> plus(IVector<A> fa2) {
                  
Google has just released [Flutter Release Preview 1](https://medium.com/flutter-io/flutter-release-preview-1-943a9b6ee65a?linkId=53249457) and [Dart Angular 5.0.0-beta](https://github.com/dart-lang/angular/releases). They have the milestone for [Dart2Stable](https://github.com/dart-lang/sdk/milestone/12) as "Due by July 10, 2018".

Any chance for a Dart 2.0 compatible release of `dartz` soon?    **Thanks**

**Comment by spebbe** [comment]
Hi @rich-j and @gedw99!

After a short eternity, I've now released version 0.8.0, which is supposed to be some kind of bridge release, with full Dart 1 support, some Dart 2 support and as few breaking changes as possible. It is more or less equivalent to the current state of the `ddc_compat` branch, but with a resuscitated test suite, some cleanups and a versioned release on pub.dartlang.org.

Starting with 0.9.0, `dartz` will probably go Dart 2 only and drop support for open higher-kinded type classes and generic monad transformers.

Many thanks for your help, patience and encouragement!

/Björn
