### ISSUE TITLE
Type defunctionalization to simulate higher kinded types

### ISSUE THREAD

**Issue by modulovalue** [spebbe/dartz#32]
Hey @spebbe,

Have you heard of type defunctionalization?

[type defunctionalization](https://www.cl.cam.ac.uk/~jdy22/papers/lightweight-higher-kinded-polymorphism.pdf)
> 1.3 Type defunctionalization
Defunctionalization transforms a program with higher-order values into a program where all values are first-order. Similarly, we can change a program with
higher-kinded type expressions into a program where all type expressions are of kind ∗, the kind of types.

### Various implementations that use type defunctionalization:
TypeScript: [fp-ts](https://github.com/gcanti/fp-ts) 
Swift: [bow](https://github.com/bow-swift/bow) and here's a [simple explanation of how it works](https://bow-swift.io/docs/fp-concepts/higher-kinded-types/)
Elm: [brands](https://github.com/joneshf/elm-brands)
Java: [HKT](https://github.com/derive4j/hkt) & [highj](https://github.com/highj/highj) & [a Medium article](https://medium.com/@johnmcclean/simulating-higher-kinded-types-in-java-b52a18b72c74)
*and (not sure if they are using the same technique)*
Rust: [Gist writeup.md](https://gist.github.com/edmundsmith/855fcf0cb35dd467c29a9350481f0ecf) & [this post](https://varkor.github.io/blog/2019/03/28/idiomatic-monads-in-rust.html)

Edit:

That wouldn't be possible with dartz as it stands now without having to do a bunch of casting, right? or am I missing something?

```dart
void main() {
  final Either<Err, String> _right = toStrAppend("?", right<Err, int>(123)).D;
  final Option<String> _some = toStrAppend("?", some(456)).D;

  print(_right.fold((err) => "$err", (a) => "value: $a"));
  print(_some.fold(() => "empty", (a) => "value: $a"));
}

Kind<F, String> toStrAppend<F, A>(String str, Functor<F, A> f) {
  return f.D.map((a) => a.toString() + "$str");
}

enum Err {
  someErr,
}
```

Output:
```
value: 123?
value: 456?
```

**Comment by spebbe** [comment]
Hi @modulovalue!

Thanks for the reference material! I've seen Bow before and I've also looked at how they encode HKTs in Arrow (Kotlin), which I think is essentially the same pattern.
Since it was possible to cheat your way out of the whole problem in Dart 1, I never implemented it then, but maybe it would be a way to get back some of the abstraction possibilities that have been removed for 0.9? I'll experiment a bit with applying this to MonadLens from the other day and see how it turns out! Might be a little while though -- December is brutal... Thanks again!

**Comment by vysarafanov** [comment]
I have some naive implementation of HKT in https://github.com/vysarafanov/javelin (look at the Laws in tests)
You're welcome to comment.
Anyway - it's absolutely annoying without typealias

**Comment by spebbe** [comment]
@vysarafanov thank you – this will help a lot in comparing approaches!
love your project, btw! much tighter structure than i currently have and a great inspiration.
i'll look into it more closely!

Also, with a bit of luck, more useful type aliases could be coming our way soon! see https://github.com/dart-lang/sdk/blob/master/tools/experimental_features.yaml section `nonfunction-type-aliases`. Also, declaration-site variance control (`variance`) is in there – fingers crossed!

**Comment by vysarafanov** [comment]
@spebbe thank you for the information, will try type aliases tomorrow.

**Comment by modulovalue** [comment]
For anyone looking into using this approach to implement more abstract constructs in Dart, I've shared an implementation of a catamorphism [here](https://github.com/dart-lang/language/issues/2880). It's a little tricky to get there from scratch, but it's a lot easier once there's some example code.

**Comment by modulovalue** [comment]
I've just noticed that this issue is still open.

Since @spebbe appears to have moved on (i.e., dartz appears to no longer be actively maintained), and there are other libraries that implement this issue (e.g. [fpdart](https://github.com/SandroMaglione/fpdart) by @SandroMaglione) I'm going to close this issue.

Thank you @spebbe for getting the ball rolling and introducing a bunch of dart developers to functional programming!
