### ISSUE TITLE
exception in function is not caught in attempt

### ISSUE THREAD

**Issue by harishrathi** [spebbe/dartz#33]
I have all my API calls returning Either<ApiException, Result> e.g.

```
  Future<Either<ApiException, SendOtpDto>> receiveOtp(
      String phoneNumber) async {
    return Task<SendOtpDto>(() async {
      final String url = 'AuthenticationApi/sendOtp/$phoneNumber';
      final Map<String, dynamic> response = await apiWrapper.get(url);
      final SendOtpDto dto = SendOtpDto.fromJson(response);
      if (!dto.success) {
        throw ServerErrorException(dto.error);
      }
      return dto;
    }).attempt().mapLeftToFailure().run();
  }

```

But if exception is thrown inside a function, like below

```
      if (!dto.success) {
        throw ServerErrorException(dto.error);
      }

```

Then `attempt()` should catch them as `ApiException`. Currently it gives error `type 'Future<Either<ApiException, dynamic>>' is not a subtype of type 'FutureOr<Either<ApiException,
SendOtpDto>>`

This is how I am calling the API

```
    if (event is GetOtpButtonPressed) {
      yield LoginApiLoading();
      final Either<ApiException, SendOtpDto> result = await apiManager.authentication(context).receiveOtp(event.username);
      yield result.fold((ApiException exception) {
        return LoginFailure(error: exception.toString());
      }, (SendOtpDto dto) {
        return LoginOtpSent(dto: dto);
      });
    }

```

**Comment by mateusfccp** [comment]
I couldn't test your code because you didn't give a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_working_example).

However, I got similar error sometimes when Dart couldn't infer the type. This may be the case, as pointed by the _dynamic_ in the error.

Try passing the type explicitily to `.attempt<T>`.

**Comment by harishrathi** [comment]
That helped. Closing the issue.

**Comment by spebbe** [comment]
Great! Thanks for helping, @mateusfccp!
