### ISSUE TITLE
await async and functional programming

### ISSUE THREAD

**Issue by heralight** [spebbe/dartz#35]
Hi!
In first, I'm impressed by your work! 
Now, I tried to use it in flutter, I was quickly block by asynchronous call problem, (await, async, then ...etc).
Have you some advice or sample about this subject please?

Best regards,

Alexandre

**Comment by mateusfccp** [comment]
Hello, @heralight.

Actually, Future, conceptually, is a monad (considering that you are not using side-effects, of course). It' all about functional programming, although the concept has been imported to procedural programming and OO as well (with `async` and `await`, for example).

Considering so, there's no kind of incompatibility between `dartz` and `Future`, although in functional style you would be using `.then` more than `async`/`await`.

Your question is a little too subjective, can you provide some example on why you are having problems? Is there anything specific that you are struggling that you may show us? So we can help you better.

Thanks, in advance.

**Comment by spebbe** [comment]
Hi @heralight!

Thanks for your support – I'm glad you like it!

Like @mateusfccp, I'm a bit unsure what exact answers you are looking for, but I'm going to take a guess that you would find `traverseFuture` useful!
`traverseFuture`, which is just a special case of the unbelievably useful `traverse` function, is defined on all `Traversable` structures in `dartz` (where I've remembered to add them, that is...).  It is your best friend when working with code that combines async computations with `Option`, `Either`, `IList`, etc.

Here are some examples:
```dart
class User { ... }

Future<User> findUser(int userId) => ...;

final Option<int> maybeUserId = userIdLookupThatMightFail(...);
final Option<User> maybeUser = await maybeUserId.traverseFuture(findUser);
final IList<int> userIds = lookupACoupleOfUserIds();
final IList<User> users = await userIds.traverseFuture(findUser);
```

**Comment by heralight** [comment]
thank you both of for your responses!
the main point why I asked this question, is due to the fact that await / async have a very good support of exceptions and a good readability.
 @spebbe, traverseFuture can help me, I will try it.
Thank you guys!
