### ISSUE TITLE
IList<Option<Tuple2<K,V>>> to IHashMap<K,V>

### ISSUE THREAD

**Issue by rich-j** [spebbe/dartz#4]
I need to convert an `IList<Option<Tuple2<K,V>>>` to a `IHashMap<K,V>`. In Scala I would use `Seq(Some("a"->1),None).flatten.toMap`. In dartz the `.flatten()` returns runtime error:

    CastError: Casting value of type 'Some<Tuple2<Stri…, String>>' to type 'IList' which is incompatible

This could be failing because I'm using DDC [Issue #2](https://github.com/spebbe/dartz/issues/2). 

For the `.toMap` equivalent:

    flattenedList.foldLeft( new IHashMap.empty(), (p, h) => p.put(h.value1, h.value2) )

Since `IHashMap` has iterators that return `Tuple2` would you consider an adding similar constructors?

**Comment by spebbe** [comment]
Added IMap#fromPairs, IHashMap#fromPairs, IList#flattenIList, IList#flattenOption, IVector#flattenIVector and IVector#flattenOption in 0.7.5 + rebased ddc_compat branch.
