### ISSUE TITLE
Flutter StatefulWidget State name collision

### ISSUE THREAD

**Issue by torbenkeller** [spebbe/dartz#41]
Since today in my Android Studio the dart compiler values the dartz import more than the material.dart import so I have to use
```dart
import 'package:dartz/dartz.dart' as dz;
``` 
when I want to use a `StatefulWidget` and some dartz objects or functions. Otherwise the app doesn't compile and throws this error message:
```
Compiler message:
lib/main.dart:31:32: Error: Expected 0 type arguments.
class _HomeWidgetState extends State<HomeWidget> {
                               ^
lib/main.dart:28:20: Error: The return type of the method 'HomeWidget.createState' is '_HomeWidgetState', which does not match the return type, 'State<StatefulWidget>', of the overridden method, 'StatefulWidget.createState'.
 - '_HomeWidgetState' is from 'package:stock_check/main.dart' ('lib/main.dart').
 - 'State' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'StatefulWidget' is from 'package:flutter/src/widgets/framework.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/framework.dart').
Change to a subtype of 'State<StatefulWidget>'.
  _HomeWidgetState createState() => _HomeWidgetState();



```

**Comment by mateusfccp** [comment]
I don't see this as a issue.
This is the default behavior for name conflict between packages, and there's indeed a `State` monad in dartz.

If your problem is having to type dz. to use dartz, you may instead import only what you need, like:

```dart
import 'package:dartz/dartz.dart' hide State; // Will import the entire package minus State
```

or

```dart
import 'package:dartz/dartz.dart' show Option; // Will import only the Option monad from dartz, everything else won't
```

**Comment by spebbe** [comment]
As @mateusfccp (thanks!) mentions above, Dart comes with excellent tools for dealing with name conflicts.

While I agree that it is unfortunate that there is a conflict to begin with, the name `State` for the specific structure in dartz is so standardized that it would be very confusing to call it anything else.

Are you ok with closing this?

**Comment by torbenkeller** [comment]
@spebbe sure. I just wanted to open this so if somebody searches for this error he will find the solution.

**Comment by spebbe** [comment]
ah, ok!

**Comment by Peng-Qian** [comment]
personally, I think it would be nice if dartz could avoid the name conflicts since lots of flutter developers are using the nice plugin. 👍

It a little bit annoying to use a prefix or hide/show (prefix will cause the syntax longer and all of them need a manually fix for every import). 😁

**Comment by mateusfccp** [comment]
I don't think so. I hardly use `StatefulWidget`s, but even when I use, my logic is decoupled of my UI, so I won't use `dartz` and `flutter/widgets` in the same file.

**Comment by Peng-Qian** [comment]
You are absolutely right, UI should be decoupled of logic. The reason I suggest here is that if we apply dartz to value object (DDD), Either() will frequently appear to UI layer.
