### ISSUE TITLE
Type Error When Returning Either From .catchError

### ISSUE THREAD

**Issue by ibcoleman** [spebbe/dartz#42]
At the risk of wearing our my welcome, do you think this is a dartz issue or a Dart issue?

```
Future<Either<Exception, StreamedResponse>> _getWithHeadersStreamed(String targetUri, JwtAuthService svc) =>
    svc.getRequestHeaders().then((headersE) =>
        headersE.fold(
                (err) => Left(err),
                (headers) {
                  Logger().i("Calling REST on $targetUri");
                  Logger().i("Auth Header is ${headers["Authorization"]}");
                  var request = Request("GET", Uri.parse(targetUri))
                    ..headers.clear()
                    ..headers.addAll(headers)
                    ..followRedirects = false;
                  return http.Client().send(request).then((value) => Right(value));
                }
        )
    ).catchError((err)  => Left<Exception, StreamedResponse>(err));
```

This works fine if I leave the .carchError call off the end. (Other than the HttpClient spewing exceptions up the call chain.) I think you mentioned something about the type system being changed in Dart 2.x. 

```
E/flutter ( 4358): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'Future<Object>' is not a subtype of type 'Future<Either<Exception, StreamedResponse>>'
E/flutter ( 4358): #0      _getWithHeadersStreamed (package:asset_management_mobile/client/tmi_client.dart:36:5)
E/flutter ( 4358): #1      returnJsonForUri (package:asset_management_mobile/client/tmi_client.dart:21:3)
E/flutter ( 4358): #2      getSystemUserSummary (package:asset_management_mobile/client/tmi_client.dart:14:5)
E/flutter ( 4358): #3      main (package:asset_management_mobile/main.dart:31:23)
E/flutter ( 4358): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter ( 4358): #5      _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 4358): #6      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 4358): #7      _runZoned (dart:async/zone.dart:1619:10)
E/flutter ( 4358): #8      runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter ( 4358): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter ( 4358): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 4358): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by spebbe** [comment]
Hi -- no worries!

I'd say it's a little bit Dart's fault and a little bit your fault :-) Just like the Scala compiler loves to infer `AnyRef` and friends, Dart has a tendency to fall back to `Object` when insufficient information for proper type inference is available.

I would highly recommend embracing `async`/`await`. It's one of the best features of Dart and is extremely well designed and implemented compared to most languages with similar features. Type inference is greatly improved compared to `then` chaining and it will be much easier to spot where type information is lost.

Although `fold` will always be able to take you where you need to go, I would also recommend the use of `map`, `flatMap` and other higher level constructs on `Either` wherever possible. They are less verbose and can also help with guiding the type inference better. Whenever you see the Left side simply being "passed through" like in the `fold` in your example, it's a sign that you probably should be using `map` or `flatMap` instead.

**Comment by spebbe** [comment]
OK if I close this? Don't hesitate to reopen if needed!

**Comment by ibcoleman** [comment]
Sure, thanks again Björn!
