### ISSUE TITLE
Either extension

### ISSUE THREAD

**Issue by rubgithub** [spebbe/dartz#44]
Sorry my newbie question, but is there a way to extend Either?

I would like to create a  `isValidReturn` method:

```
class MyExtension extends Either {
  @override
  B fold<B>(B Function(dynamic) ifLeft, B Function(dynamic) ifRight) {
    // TODO: implement fold
    throw UnimplementedError();
  }

  bool isValidReturn() => isRight(); 
}
```

**Comment by spebbe** [comment]
Hi – no probs!

I would recommend against inheriting from `Either`, but using extension methods (https://dart.dev/guides/language/extension-methods) it's easy to add convenience/util stuff:
```dart
extension MyEitherStuff on Either {
  bool isValidReturn() => isRight();
}
```

**Comment by rubgithub** [comment]
Thanks, you're `R` extension is  the best choice.  =)
