### ISSUE TITLE
flutter_test expect throws error on Right with List

### ISSUE THREAD

**Issue by adamsmaka** [spebbe/dartz#45]
Hi, I cannot test dartz Right value when type is a list.
```
  Either<dynamic, List<String>> getStrings() {
    return Right(['Two', 'Three']);
  }
```
```
      test(
        'STRINGS',
        () {
          final result = repository.getStrings();
          expect(result, equals(Right(['Two', 'Three'])));
        },
      );
```
The code above throws error:

> ERROR: Expected: Right<dynamic, List<String>>:<Right([Two, Three])>
>   Actual: Right<dynamic, List<String>>:<Right([Two, Three])>

What am I doing wrong?

**Comment by adamsmaka** [comment]
Even code like this doesn't work :(
`expect(Right(['Two', 'Three']), equals(Right(['Two', 'Three'])));`

**Comment by mateusfccp** [comment]
@adamsmaka Your problem probably has nothing to do with `dartz`. The same would happen if you was simply comparing the two inner lists, because this is how Dart works regarding lists comparision. It will compare the hashcodes, instead of the list items.

Have a look at #39, the issue is the same.

**Comment by spebbe** [comment]
As @mateusfccp writes, this is expected behaviour of `List` equality. If you are able/willing to use `IList` instead of `List`, it provides more intuitive default equality semantics, e.g `expect(Right(ilist(['Two', 'Three'])), equals(Right(ilist(['Two', 'Three']))));` will succeed.

**Comment by adamsmaka** [comment]
I did something like that and it works 🤔
```
          if (result.isRight()) {
            final resultIList = result.getOrElse(null);
            expect(resultIList, equals(myList));
          }
          expect(result.isRight(), true);
```
Anyway thanks for answers!

**Comment by spebbe** [comment]
Yes, the test framework includes special treatment for naked `List` instances. OK to close?
