### ISSUE TITLE
Switch Alternative

### ISSUE THREAD

**Issue by rubgithub** [spebbe/dartz#48]
I was looking for a functional alternative and I found `mach`
```
match(50)
  .on(x => x < 0, () => 0)
  .on(x => x >= 0 && x <= 1, () => 1)
  .otherwise(x => x * 10)
// => 500
```
Is there something similar in dartz?  

https://codeburst.io/alternative-to-javascripts-switch-statement-with-a-functional-twist-3f572787ba1c

**Comment by spebbe** [comment]
hi!

hmm... i guess you could layer this on top of `Either` using these helpers:
```dart
extension Matching<L, R> on Either<L, R> {
  Either<L, R> on(bool predicate(R r), L value()) => flatMap((r) => predicate(r) ? left<L, R>(value()) : right<L, R>(r));
  L otherwise(L transformation(R r)) => fold(id, transformation);
}

Either<Result, A> match<A, Result>(A a) => right(a);
```

then you could could do:
```dart
  final result = match<num, num>(2)
    .on((x) => x < 0, () => 0)
    .on((x) => x >= 0 && x <= 1, () => 1)
    .otherwise((x) => x*10);
```

o'm not necessarily recommending this approach and i wouldn't claim that it's more "functional" than side effect free functions with normal conditionals/switches in them, but it's an interesting use case!
