### ISSUE TITLE
{excuse me for offtop but...}: What's does the idiom  'QuickCheck' mean?

### ISSUE THREAD

**Issue by ValeriusGC** [spebbe/dartz#49]
Hi! Some offtop but i really intrigued. I saw it in the tests:
```
final qc = new QuickCheck(maxSize: 300, seed: 42);
```
This class has no fields for constructor arguments, so i am stucked what goal is for them?

**Comment by spebbe** [comment]
hi! it's a property based testing system. there's good information and a some links about it here: https://github.com/polux/propcheck .

sadly, the implementation above hasn't been updated for Dart 2, so I'm currently using a very poor replacement for it in `dartz`, resulting in less reliable tests until i've found/built a better engine.

**Comment by ValeriusGC** [comment]
I saw that project when I surfed web with this my issue. But his `QuickCheck` filled with appropriate fields so I understood that approach. As for yours one, this is just stub, isn't it? If so I got it.
--
Would You give me a favor and explain my another question (#50)? Thanks in advance.

**Comment by spebbe** [comment]
right, yes! the stubs adhere to the original contract in the hope that i will be able to plug in a full implementation eventually.

i'll look into the other tickets when i have a little more time!
