### ISSUE TITLE
After return from Left or Right, still next line is why executing?

### ISSUE THREAD

**Issue by MuthuHere** [spebbe/dartz#51]
In my api call i am returning response object in right and error message in left.

![image](https://user-images.githubusercontent.com/18752533/87003354-0b0d0000-c1ee-11ea-985e-5ca721499444.png)

See i am getting the print line execution.
Quite weird 
![image](https://user-images.githubusercontent.com/18752533/87003613-8ec6ec80-c1ee-11ea-8f29-639588141c2d.png)

**Comment by krevedkokun** [comment]
nothing weird, you're just returning from closure not function

**Comment by MuthuHere** [comment]
any clue ? @krevedkokun

**Comment by krevedkokun** [comment]
it's hard to tell what you're trying to achieve from that snippet

**Comment by MuthuHere** [comment]
Here you go,

This is a class to return loginResponse once it get success i am returning LoginModel if not i am returning error.

![image](https://user-images.githubusercontent.com/18752533/87006105-adc77d80-c1f2-11ea-9222-cf6e02a5d196.png)

**Comment by spebbe** [comment]
Hi! As @krevedkokun said, you need to `return` the result of `fold`. Your current code should produce a warning about not returning a proper value from `userLogin` – that's probably what the yellow squiggly line is about.
This is normal and expected in Dart. The Dart language doesn't have non-local returns.

**Comment by MuthuHere** [comment]
@spebbe  yes, got it but it gives error :-(



![image](https://user-images.githubusercontent.com/18752533/87008143-e61c8b00-c1f5-11ea-8728-2c9d6b3bce7b.png)

**Comment by spebbe** [comment]
I'm not sure what you are trying to do here, but please check your types in your editor of choice, as they do not currently line up correctly. `data` can _never_ be of runtime type `LoginModel`. Your should be able to `return response.fold(...)` directly, although some additional type annotations might be necessary.

I highly recommend adding `pedantic` or `extra_pedantic` to your project. They will help you spot a lot of problems statically, including type issues like these.
