### ISSUE TITLE
How to split a conveyor/stream into two

### ISSUE THREAD

**Issue by michaelzingg** [spebbe/dartz#52]
I am aware that the conveyor stuff is still experimental, and I am only using it to try out a few things.
There are many methods which can be used to merge streams (plus, interleave, zip, ...). However, I found no way to split one stream into two, or write to multiple files/sinks. Is there a way to do that or would I need to extend the existing streaming framework?

**Comment by spebbe** [comment]
Hi -- cool that you are trying it out!

I'm not sure if this is what you're after, but here's a simple example of writing to multiple files concurrently using channels and `through`:
```dart
Conveyor<Free<IOOp, Object>, ChannelF<Free<IOOp, Object>, A, A>> dumpToFile<A>(String path) => Source.resource(
    io.openFile(path, false),
      (FileRef file) => Source.constant(IOM, (A a) => Source.eval(io.writeBytes(file, ilist(utf8.encode("$a\n"))).replace(a))),
      (FileRef file) => Source.eval_(io.closeFile(file)));

  final c = Source.intsFrom(IOM, 1)
    .through(dumpToFile("all.txt"))
    .filter((i) => i%2==1)
    .take(10)
    .through(dumpToFile("odd.txt"))
    .drain();
```

If you run it with `mockConveyIO` (in the examples folder), you'll see that the writes to the files are actually interleaved and streaming.

As you've probably noticed there aren't many high level APIs/utils for Conveyor yet, but hearing what kind of problems you are trying to solve might give rise to some new ones?

Cheers!

**Comment by michaelzingg** [comment]
Thank you @spebbe 
Your example helped me to look at the conveyor code from a different angle and I think I am a little closer to understand how it works. I am planning to read the chapter in "Functional Programming in Scala" you referenced in the source file. Hopefully it will help me to get an even better understanding of the concepts you used for the conveyor implementation.

I am learning Flutter right now and to make it more interesting I gave myself the task of implementing a simple todo app following the rules of todo.txt format. Since I also have an interest in functional programming I decided to see if I can find an elegant solution by using the dartz library. So here is my use case:

In todo.txt all the todos are kept in a simple text file, where every line represents one todo. Most todo.txt apps support the feature to archive all completed tasks into an archive file. So what I would need for this, is to read the todo file, filter out all completed todos, append them to the archive file and dump the rest back into the todo file.
It is similar to what you already demonstrated in your example, with some small adaptions. It is like reading the "all.txt" file and writing the odd numbers to "odd.txt" and the even numbers back to "all.txt"

To solve this problem I would need to be able to split the stream into two and apply individual filters to both of them afterwards before writing them back to a file. I am sure it is possible, I just haven't figured out how.

**Comment by spebbe** [comment]
@michaelzingg, i'm not claiming that this is a particularly elegant or efficient solution, but here's one straight forward way of doing it:
```dart
  Conveyor<Free<IOOp, Object>, ChannelF<Free<IOOp, Object>, A, A>> toFile<A>(String path, Option<String> transform(A a)) => Source.resource(
    io.openFile(path, false),
      (FileRef file) => Source.constant(IOM, (A a) {
        final writeOp = transform(a).fold(() => IOM.nothing, (s) => io.writeBytes(file, ilist(utf8.encode("$s\n"))));
        return Source.eval(writeOp.replace(a));
      }),
      (FileRef file) => Source.eval_(io.closeFile(file)));

  final c = Source.intsFrom(IOM, 1)
    .take(10)
    .through(toFile("all.txt", (i) => some("$i")))
    .through(toFile("odd.txt", (i) => option(i%2==1, "$i")))
    .through(toFile("even.txt", (i) => option(i%2==0, "$i")))
    .drain();
```

Actually splitting a `Conveyor` into two or more is probably going to be a bit messy. Being a pull style streaming approach, dealing with back pressure, error propagation and resource safety in a "split" scenario might require some compromises for the general case.

I'm not sure if the https://fs2.io/ people have found a better way to deal with this since I last studied it, but I believe they used to recommend switching to push style through the use of queues if one _really_ needed actual splitting.

**Comment by michaelzingg** [comment]
Hi @spebbe 
Thanks for your solution. I think it will do for my use case, but I see, that it probably gets messy very quickly if there are more operations involved. It looks like splitting streams is not that easy. I have not seen any language or library which supported splitting streams elegantly. Recently, I saw an example of Akka streams and substreams which looked cool, but I have not found the time to look into it in detail. I will definitely have another look at the fs2 repository for inspiration.

**Comment by spebbe** [comment]
closing this for now, but feel free to re-open if needed!
