### ISSUE TITLE
No rightMap on Either?

### ISSUE THREAD

**Issue by reilem** [spebbe/dartz#56]
Currently `Either` has a `leftMap` but no `rightMap`. Is there any reason for this that I am not seeing?

It's a one line fix and I would gladly open a PR for it. 😄

**Comment by spebbe** [comment]
Hi @reilem!

`Either` is right biased, so the existing `map` method should do what you want, unless I misunderstood what you want :-)

**Comment by reilem** [comment]
You are indeed right, I didn't see the `map` function (or didn't fully understand what it did at first). Thanks!
