### ISSUE TITLE
flatMap lower bound on left type

### ISSUE THREAD

**Issue by prascuna** [spebbe/dartz#57]
Hi there,
First of all, thanks for this nice library! Coming from Scala it makes my Dart-life way easier...

I'm trying to model a family of error types as it follows, but I'm having troubles composing them through an `Either`.

```dart
abstract class MyError {
  final String message;

  const MyError(this.message);
}

class ErrorOne extends MyError {
  const ErrorOne(String message) : super(message);
}

class ErrorTwo extends MyError {
  const ErrorTwo(String message) : super(message);
}
```

Assuming I have two methods that return the following...

```dart
  Either<ErrorOne, int> firstStep() {
    return Right(123);
  }

  Either<ErrorTwo, String> secondStep(int value) {
    return Right(value.toString());
  }
```

... I try to compose them like shown below:
```dart
    firstStep().flatMap((a) => secondStep(a)).fold(
        (left) => print('got left: ${left.message}'),
        (right) => print('got right'));
```

Unfortunately I get this compile time error:
` Error: A value of type 'Either<ErrorTwo, String>' can't be assigned to a variable of type 'Either<ErrorOne, dynamic>'.`

Would it be possible to have a flatMap with a signature similar to Scala's, that returns a super class of the given left type as the new left type?
```scala
  def flatMap[A1 >: A, B1](f: B => Either[A1, B1]): Either[A1, B1]
```

The only way I made this work is by changing both methods `firstStep` and `secondStep` to return an `Either<MyError, xxx>` though I don't like this solution that much, as in my real world scenario they belong to different services and each of them has got its own family of errors.

Can you think of something else to make it work?

Thanks!

**Comment by spebbe** [comment]
Hi @prascuna! Glad you find it useful!

Last time I checked, Dart simply didn't support lower bounds for generic type parameters :-( Unless someone knows of some trick or workaround that I've missed, I'm afraid the type contract you suggested cannot be expressed statically for now.

A somewhat silly and noisy workaround is to widen `L` using `leftMap`, like this:
```dart
firstStep().leftMap<MyError>(id).flatMap(secondStep).fold(...)
```

Hope that helps a little!

**Comment by prascuna** [comment]
Thanks @spebbe , that's actually a way better solution than mine, so I'll take it! :) 
Finger crossed, dart's type system will get better with time... I think what you did with this library is an outstanding piece of work!
