### ISSUE TITLE
Map arity

### ISSUE THREAD

**Issue by cranst0n** [spebbe/dartz#61]
Is there any reason the arity of `.mapN` (e.g. `Either.map1`, `Either.map2`, etc.) only goes up to 6? I've run into a situation where I could actually use functions that handle a higher number of arguments. Or maybe there's a more elegant solution (e.g. some kind of for comprehension-like feature) that I'm unaware of?

I can open a pull request if you're okay with this and don't want to do the mechanical tidbits. Just wanted to check ahead of time.

Thanks for the nice library!

**Comment by spebbe** [comment]
Hi @cranst0n and thanks for your interest!
I think I just got bored at some point :-)
Should probably have some code generators for this, but a PR with more hand written cases would be great!

**Comment by cranst0n** [comment]
Fixed in #62.

**Comment by spebbe** [comment]
@cranst0n, my apologies for the long wait. I've now released 0.9.2 with the contents of PR #62! I haven't been able to find the time for completing the stuff I was working on and will release them later instead. Thanks again!
