### ISSUE TITLE
Support Dart null safety

### ISSUE THREAD

**Issue by eggnstone** [spebbe/dartz#70]
Please support Dart null safety
https://dart.dev/null-safety

**Comment by mateusfccp** [comment]
I was thinking about it today, but it will require @spebbe drop Dart 1 support first, and I don't know when he is willing to do it.

**Comment by spebbe** [comment]
okidoki! i'm preparing one of those `-nullsafety` prerelease packages. almost there, just a couple of pesky test failures to fix.

**Comment by mateusfccp** [comment]
@spebbe So are you finally dropping Dart 1 support?

**Comment by spebbe** [comment]
@mateusfccp I'll do the initial `-nullsafety` prereleases from a branch and AFAIK that branch will have to specify 2.12 as minimum SDK requirement, so in a way: yes! Sometime after null safety is out of beta, this branch would be merged to master and I think Dart 1 backwards compatibility will be then become impossible to retain.

**Comment by spebbe** [comment]
Hi @eggnstone and everyone else! I've published `0.10.0-nullsafety.0` now. All tests pass and the examples run correctly, but there could still be regressions and/or unintended behaviour. Please report any issues you find!

**Comment by apiep** [comment]
may I ask when will dartz with nullsafety promoted to stable release with flutter 2.0 has been released in which include nullsafety?

**Comment by spebbe** [comment]
The first stable releases on the Dart 2.12 and Flutter 2.0 tracks were released yesterday. I myself am going to wait for at least a couple of patch releases until I convert customer facing applications (i've been burnt before 😁) and would therefore not want to require >=2.12 on the main releases just yet. The patch versions tend to come quite quickly after major SDK releases though, so it shouldn't be too long.

**Comment by JAAvander** [comment]
I noticed a problem regarding the result types in various functions, such as returning from a call to `when`, or from a `fold`, when these are nullable. 
A more elaborate example is this:
```dart
potentialFailure.fold<String?>(
  (failure) => "There was a problem",
  (validValue) {
    // doing something else
    return null;
  },
);
```

Maybe this use of folding wouldn't make much sense. That being said, it should be valid code, correct?  
But the the dart analyzer would complain and say that `String? is not a subtype of Object`. Furthermore the same happenes when trying to make an effectfull fold, and returning void.  
This seems to be caused by the generic `T` having to extend `Object`. Is this restriction necessary?

**Comment by moseskarunia** [comment]
> I noticed a problem regarding the result types in various functions, such as returning from a call to `when`, or from a `fold`, when these are nullable.
> A more elaborate example is this:
> 
> ```dart
> potentialFailure.fold<String?>(
>   (failure) => "There was a problem",
>   (validValue) {
>     // doing something else
>     return null;
>   },
> );
> ```
> 
> Maybe this use of folding wouldn't make much sense. That being said, it should be valid code, correct?
> But the the dart analyzer would complain and say that `String? is not a subtype of Object`. Furthermore the same happenes when trying to make an effectfull fold, and returning void.
> This seems to be caused by the generic `T` having to extend `Object`. Is this restriction necessary?

Hi. Almost everything except from null extends from Object. I think that's to prevent nullable from being a Right value.

**Comment by spebbe** [comment]
@JAAvander , @moseskarunia: Somewhat controversially so, `Left` and `Right` values _can_ actually carry `null` values when given nullable type arguments. The code above works fine for me on Dart 2.12.2. Are you maybe trying to use (assign, return, etc) the return value from `fold` in a non-nullable context? For example, `final Object o = potentialFailure.fold<String?>(...)` would be a type error, whereas `final Object? o = potentialFailure.fold<String?>(...)` is fine.

**Comment by spebbe** [comment]
@wondertalik, try changing `Right(tClient)` to `Right<Failure, Client>(tClient)`. I don't think it is possible for mockito's `thenAnswer` to correctly infer all types. Using `pedantic` or `extra_pedantic` should help flag cases where `dynamic` is inferred.

**Comment by moseskarunia** [comment]
@wondertalik this kinda unrelated, but mockito kinda messed up with null-safety. Use mocktail instead.

**Comment by wondertalik** [comment]
> @wondertalik, try changing `Right(tClient)` to `Right<Failure, Client>(tClient)`. I don't think it is possible for mockito's `thenAnswer` to correctly infer all types. Using `pedantic` or `extra_pedantic` should help flag cases where `dynamic` is inferred.

Thanks. It works.

**Comment by lukertaylor** [comment]
@moseskarunia, thank you for the tip about Mocktail - much cleaner without code generation 💯

**Comment by domzinhuu** [comment]
magnific tip @moseskarunia,  worked like a charm!

**Comment by eggnstone** [comment]
The dev preview has been out for 2 months now. 
Please release it as an official version.

**Comment by DanielCardonaRojas** [comment]
I also have package  called `verify` with a nullsafe-prerelease and dartz as a dependency, is there an estimate as to when this will become an official version?

**Comment by spebbe** [comment]
Hi @eggnstone and @DanielCardonaRojas! Sorry for the long wait – a stable release `0.10.0` has now been published!
