### ISSUE TITLE
Is Option necessary with nullsafety?

### ISSUE THREAD

**Issue by Nolence** [spebbe/dartz#71]
Hi!

Sorry if this is a dumb question or if it belongs on SO.

Now that dart has sound null safety, we can be certain something is not null. The compiler (or whatever it is) is even smart enough to promote things to non-null after we check its not equal to null. `Option`'s main selling point to me was requiring we handle the case where a value was possibly null but is there still a reason to use it now? Using `Object?` in place of `Object` is even a compilation error now.

Thanks!

**Comment by mateusfccp** [comment]
Yes, it is. Option is not only a solution for null-safety. It has all the functorial/monadic properties that null-safety doesn't provide. However, if your only case for Option was for null-safety, you can simply not use it.

**Comment by spebbe** [comment]
Hi – not a dumb question at all!

Dart null safety is still in beta, but is expected to be available in a stable SDK soon-ish. Once that happens, null safety benefits similar to what is provided by `Option` will be supported natively in the language. `?` specifies partiality in the type system just as well as `Option` does and carries less runtime and syntactic overhead. There will probably still be cases where combinators on `Option`, such as `flatMap`, `Option.mapX` and so on will produce subjectively prettier code, but all in all I expect the need for `Option` to be greatly reduced for the purposes of null safety.

Like @mateusfccp mentions, for programming in a pure functional style, `Option` still has relevance though.
It might be possible to simulate operations such as `traverseOption` and `sequenceOption` on `IList<A?>` etc using extension methods and make it possible to treat `?` like an ersatz `Option` monad for practical purposes, but I will have to experiment a bit with it.

**Comment by Nolence** [comment]
Sounds good and thanks for the explanation.

Yeah, my first introduction to this library was through a prior colleague telling me to just use it to get rid of null's in our codebase so I had a somewhat limited POV. I still do like how nice the combinators look over alternative methods.

Thank you
