### ISSUE TITLE
2nd API depends on 1st API - how can I do this?

### ISSUE THREAD

**Issue by ericchuawc** [spebbe/dartz#73]
I need some help here. I learned this library from this tutorial https://resocoder.com/2019/12/14/functional-error-handling-in-flutter-dart-2-either-task-fp/ and single API call seemed to work.

However I have this scenario

1st API - https://ip/v1/programs - this API will return all programs

Then, in order to get the programs' photo, I need to call another API and do a for loop.

2nd API - https://ip/v1/programs/id/photo - the id is passed from 1st API and photo is in binary bytes

Basically I need to call 2nd API after I call 1st API. Then assign the photo into each program from the List return from 1st API.

Note: program.dart (used freezed package) and it's immutable. Has id, photo, etc fields.

My codes

```
Either<NetworkExceptions, List<Program>> _result;
  Either<NetworkExceptions, List<Program>> get result => _result;
  void _setResult(Either<NetworkExceptions, List<Program>> result) {
    _result = result;
  }

Future<void> getPrograms() async {
await Task(() => _service.getPrograms(token))
.attempt()
.mapLeftToFailure()
.run()
.then((value) => _setResult(value));

result.fold(
(failure) => {}
(programs) async {
// call 2nd API here ???
}
);

Future<List<Program>> getProgramPhoto(Token token, List<Program> old) async {
List<Program> newProgram;

old.forEach(
(program) async {
 await Task(() => _service.getProgramPhoto(token, program.id))
.attempt()
.mapLeftToFailure()
.run()
.then((value) => ??);
}
);
}
```

Questions

1. Not sure the way I write my codes is correct. Any idea?
2. Any idea how do I assign photo (Uint8List) to an existing List<Program> as Program is immutable?

**Comment by spebbe** [comment]
Hi @ericchuawc!

This sounds similar to the issues #34 and #69, to name a few. Would the information and suggestions in those tickets maybe help you achieve what you want?

**Comment by ericchuawc** [comment]
In my await Task(), I have tested to call _service.getPrograms(token). Inside the getPrograms(), I will process the 2 API calls. Seems to work fine.

Do you think this is a good way?

or is it better I handle this 2 APIs from Task() ?

**Comment by spebbe** [comment]
Hi @ericchuawc!

It really depends on what your goals are. If your code does what you want it to do and you like the way it looks, it's probably a good way :-)
Whether the `Future` passed to `Task` performs a single API call or a whole sequence doesn't really matter much from a functionality perspective. `Task` combinators such as `attempt()` will work fine regardless.
Wrapping each API call in a separate `Task` might improve certain aspects of your code, such as composability and testability, but it is very much up to how you prefer to structure your code.

**Comment by wenchingchua** [comment]
Thanks for sharing.

If I want to do this "**Wrapping each API call in a separate Task might improve certain aspects of your code, such as composability and testability, but it is very much up to how you prefer to structure your code.**"

As 2nd API call depends on 1st API call, how do I write this code? Any code snippets to share?

**Comment by ericchuawc** [comment]
Thanks for sharing.

If I want to do this "Wrapping each API call in a separate Task might improve certain aspects of your code, such as composability and testability, but it is very much up to how you prefer to structure your code."

As 2nd API call depends on 1st API call, how do I write this code? Any code snippets to share?

**Comment by ericchuawc** [comment]
I found out that I can do concurrent APIs using this way

```
await Task(() {
      final values = Future.wait([
        _service.callAPI1(), // return Class1
        _service.callAPI2(), // return Class2
        _service.callAPI3(), // return Class3
      ]);
      return values;
}).attempt()...
.then((value) => // process List<dynamic> (so in this List, I have 3 objects of Classe1,2,3.
```

But wonder can 2nd API depends on 1st API, I handle within Task() itself. Hmm...

**Comment by spebbe** [comment]
Hi @ericchuawc!

Here's a toy example showing some strategies for composing `Task` instances using `map` and `flatMap`, as well as integration with `Future` primitives such as `wait`. Maybe it will give you some ideas of possible ways for structuring your code?:
```dart
import 'package:dartz/dartz.dart';

main() async {
  Task<String> getNumericString({bool fail = false}) =>
    Task.delay(() => "12345" + (fail ? "!" : ""));

  Task<List<String>> splitString(String s) =>
    Task.delay(() => s.split(""));

  Task<int> stringToInt(String s) =>
    Task.delay(() => int.parse(s));

  Task<List<int>> stringsToInts(List<String> ss) =>
    Task(() => Future.wait(ss.map(stringToInt).map((t) => t.run())));

  Future<void> runProgram({bool fail = false}) async {
    final task = getNumericString(fail: fail)
      .flatMap(splitString)
      .flatMap(stringsToInts)
      .map((ints) => ints.fold(0, IntSumMi.append));

    print(await task.attempt().run());
  }

  await runProgram(fail: false);
  await runProgram(fail: true);
}
```

**Comment by ericchuawc** [comment]
Thanks for sharing @spebbe and will see how to implement such approach in my codes soon.
