### ISSUE TITLE
Null safe optionOf should accept null

### ISSUE THREAD

**Issue by rich-j** [spebbe/dartz#74]
The `Option` method `optionOf` needs to accept a nullable value since its function is to remove said null...

```dart
Option<A> optionOf<A>(A? value) => value != null ? some(value) : none();
```

Using `dartz: ^0.10.0-nullsafety.0`

**Comment by spebbe** [comment]
Hi @rich-j!

Haha – I feel really silly now :-) Thanks for spotting this! I'll publish a fix as soon as I'm able!

**Comment by rich-j** [comment]
Not a problem @spebbe - we're all trying to learn the new null nuances...

We now find that converting an `Option` back to a nullable type (needed for some Flutter APIs) is not as clean as it used to be. Given an `Option<String> str` we used to convert with `str | null` - this now doesn't type check. We have found `str.fold(()=>null,(s)=>s)` but would like something a little more concise. Would you consider adding a method like `.getOrNull` (implemented with the above `fold`) or any other ideas? Thanks!

**Comment by apiep** [comment]
For me, using a simple method extension is enough :D
Here is an example https://github.com/qiscus/qiscus-chat-sdk-flutter/blob/master/lib/src/core/extension.dart#L181

**Comment by rich-j** [comment]
@apiep - yes, using extension methods is a good suggestion for conversions from `Option` (still need the original issue's change to `optionOf`). We already had a `.get` extension (throws on `None` - inspired by Scala) and we did add the `.getOrNull` as an extension. I made the above suggestion of adding a conversion back to a nullable type in `dartz` to maybe provide "balance" to the API. `optionOf` converts a nullable type "to" an `Option` (and removes the nullable aspect), so what's the corresponding "from" conversion? I am good with an extension.

**Comment by spebbe** [comment]
@apiep, @rich-j, thanks for the input! I think adding an explicit `A? toNullable()` to `Option` makes perfect sense on the `nullsafety` release track for now. It will of course make it into `master` eventually. I've previously tried hard to avoid API methods that intentionally return `null`, but with Dart null safety (once stable) I feel it's safe to chill a bit on that point.

**Comment by rich-j** [comment]
@spebbe, any chance of a release - at least for the parameter type? 

I can fork - but that seems like a lot of work for a single "?"  ;-)

**Comment by spebbe** [comment]
@rich-j, @apiep: `0.10.0-nullsafety.1` published now with the discussed changes!

**Comment by rich-j** [comment]
Thanks @spebbe - our development CI builds are happy again (I admit I "cheated" and added the "?" to my local `dartz` copy)
