### ISSUE TITLE
Is there a Try?

### ISSUE THREAD

**Issue by najibghadri** [spebbe/dartz#79]
Hello. Say I have a function () => A that might throw an error. Is there a monad/function that turns it into an Option. Afaik this is called Try. There is IOMonad and Free monad but I can't figure out they serve this purpose.

**Comment by najibghadri** [comment]
Obviously I can make my own, but still, wondering what is the standard here.
```
tryOf(Function f) {
  try {
    return optionOf(f.call());
  } catch (e) {
    return None();
  }
}
```

**Comment by ibcoleman** [comment]
@najibghadri The only thing I see like that is Either's catching function... but that's not quite it.

**Comment by spebbe** [comment]
@najibghadri, the `catching` function that @ibcoleman mentions is probably the closest thing in `dartz` at the moment. It returns `Either` values, capturing any thrown exceptions as `Left` values, but if you want to discard any captured exception information you can always do
```dart 
final maybeResult = catching(() => ...).toOption();
```

**Comment by ibcoleman** [comment]
Ok, I can't hold back any longer...

![image](https://user-images.githubusercontent.com/1636877/119160818-a6821a80-ba26-11eb-99ff-5c0abf0ea4d6.png)

**Comment by najibghadri** [comment]
This is it, lovely, thank you guys! 😊  🙏

**Comment by najibghadri** [comment]
@ibcoleman And yes, I love the running joke.. There is no Try and that's it.
