### ISSUE TITLE
When null-safety version will  released?

### ISSUE THREAD

**Issue by toshiossada** [spebbe/dartz#82]
Currently the realesed vesion in pub.dev is 0.9.2 and the nullsafety version 0.10.0-nullsafety.2 is in pre-released?
When 0.10.0-nullsafety.2 will be released?

![image](https://user-images.githubusercontent.com/2637049/127332311-c6bc39c4-5052-49da-8f6b-1b41bad7fe9e.png)

**Comment by newlifeappx** [comment]
Same question )

**Comment by wferem1** [comment]
Hi @spebbe,

Any update on when this stable release will be available?

**Comment by spebbe** [comment]
Hi @toshiossada, @newlifeappx and @wferem1! Sorry for the long wait – a stable release `0.10.0` has now been published!

**Comment by toshiossada** [comment]
@spebbe thanks
