### ISSUE TITLE
Testing with Left data/class keep failing.

### ISSUE THREAD

**Issue by yusufa445** [spebbe/dartz#94]
Hi, Dartz community,
I have another Issue when testing left data from either.

```
test('should return server failure when remote data is unsuccessful',
          () async {
        // arrange
        final ServerFailure sv = ServerFailure();
        when(mockNetworkInfo.isConnected).thenAnswer((_) async => true);
        when(mockRemoteDataSource.getConcreteNumberTrivia(any))
           .thenThrow(ServerException());
        // act
        final result = await repository.getConcreteNumberTrivia(tNumber);

        result.fold((l) {
          verify(mockRemoteDataSource.getConcreteNumberTrivia(tNumber));
          verifyZeroInteractions(mockLocalDataSource);
          expect(l, ServerFailure());
        }, (r) {
          fail("shouldn't returning right data");
        });
```
      
this is my repository code.
      
```
@override
  Future<Either<Failure, NumberTrivia>> getConcreteNumberTrivia(
      int? number) async {
    networkInfo.isConnected;
    try {
      final remoteTrivia =
      await remoteDataSource.getConcreteNumberTrivia(number);
      localDataSource.cacheNumberTrivia(remoteTrivia);
      return Right(remoteTrivia);
    } on ServerException {
      return Left(ServerFailure());
    }
  }
```
      
That test would be resulting in this error
**Expected: <Instance of 'ServerFailure'>
Actual: <Instance of 'ServerFailure'>**
  
  I've made sure that ServerFailure has come from the same file and class.
  
  
  Thanks.

**Comment by spebbe** [comment]
Hi @yusufa445! Does `ServerFailure() == ServerFailure()` evaluate to `true`? That is, have you overridden `operator ==` to implement structural equality? If not, the behaviour you describe is expected, since Dart defaults to reference equality. You might want to try `expect(l is ServerFailure, true);` or something similar instead?

Good luck!
