### ISSUE TITLE
[Doubt] where was declared and implemented the functions ifRight and ifLeft?

### ISSUE THREAD

**Issue by cindRoberta** [spebbe/dartz#96]
where was declared and implemented the functions `ifRight` and `ifLeft`?

**Comment by spebbe** [comment]
Hi @cindRoberta!

I'm afraid I don't really understand your question. In case you are referring to the named arguments `ifLeft` and `ifRight` to `Either#fold` then those are just names of function arguments that callers are supposed to supply.

Please supply more context if you are asking for something else!

**Comment by cindRoberta** [comment]
```dart
B fold<B>(B ifLeft(L l), B ifRight(R r));
```
is a syntax sugar for:
```dart
B fold<B>(B Function(L l) ifLeft, B Function(R r) ifRight);
```
